name: Command Inbox
description: VoltAI Operator için doğal dille talimat bırakın (komut yazmadan).
title: "OPERATE: {kısa başlık}"
labels: ["voltai-operator", "inbox"]
assignees: []
body:
  - type: textarea
    id: intent
    attributes:
      label: Talimat (doğal dil)
      description: Ne yapmak istiyorsun? Normal cümlelerle yaz. Örn: "Günlük rapora şu 5 kaynağı ekle, acil maddelere şunları yaz."
      placeholder: |
        - iPhone Repair Atlas yeni kaynaklar: ...
        - Sponsor lead: ...
        - Affiliate blokları: ...
        - Acil aksiyon: ...
    validations:
      required: true