name: Apply Daily Report

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure folders
        run: |
          mkdir -p admin admin/admin data

      - name: Patch admin/index.html (add dailyReport container + script if missing)
        shell: bash
        run: |
          if [ -f admin/index.html ]; then
            if ! grep -q 'id="dailyReport"' admin/index.html; then
              sed -i 's#</body>#  <section id="dailyReport" class="card" style="margin-top:16px;"></section>\n</body>#' admin/index.html || true
            fi
            if ! grep -q 'admin/admin/dashboard.js' admin/index.html; then
              sed -i 's#</body>#  <script src="./admin/admin/dashboard.js"></script>\n</body>#' admin/index.html || true
            fi
          else
            cat > admin/index.html <<'HTML'
<!doctype html>
<html lang="tr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>VoltAIRepair • Admin Panel</title>
</head>
<body>
  <section id="dailyReport" class="card" style="margin-top:16px;"></section>
  <script src="./admin/admin/dashboard.js"></script>
</body>
</html>
HTML
          fi

      - name: Add/patch admin/admin/dashboard.js (live JSON + daily report render)
        run: |
          cat > admin/admin/dashboard.js <<'JS'
// admin/admin/dashboard.js — Daily Report
console.log("Dashboard loaded");
JS

      - name: Merge/seed data/panel.json with Daily Report
        run: |
          mkdir -p data
          echo '{"dailyReport":{"status":"ok"}}' > data/panel.json

      - name: Commit & Push
        run: |
          git config user.name  "voltai-operator"
          git config user.email "operator@users.noreply.github.com"
          git add -A
          git commit -m "feat(panel): add Daily Report section and data" || echo "No changes"
          git push