name: Apply Daily Report

on:
  # PR açıldığında (veya güncellendiğinde) otomatik devreye girsin
  pull_request:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'admin/**'
      - '.github/workflows/apply-daily-report.yml'

permissions:
  contents: write        # main'e push için gerekli
  pull-requests: write   # gerekirse PR durumlarını güncellemek için

jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest

    steps:
      # 1) main dalını tam geçmişle al
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      # 2) PR şube adını al ve içeriğini indir
      - name: Fetch PR branch
        run: |
          echo "PR branch: ${{ github.event.pull_request.head.ref }}"
          git fetch origin "${{ github.event.pull_request.head.ref }}":"${{ github.event.pull_request.head.ref }}"

      # 3) PR şubesini main'e birleştir (otomatik commit)
      - name: Merge PR branch into main
        run: |
          git config user.name  "voltai-operator"
          git config user.email "operator@users.noreply.github.com"
          git checkout main
          git merge --no-ff "${{ github.event.pull_request.head.ref }}" -m "auto: apply PR #${{ github.event.pull_request.number }}"
          git push