name: Auto Cleanup (safe)
on:
  workflow_dispatch: {}
jobs:
  tidy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Fix pages essentials
        run: |
          touch .nojekyll
          echo "<!doctype html><meta charset='utf-8'><title>404</title><h1>404 Not Found</h1>" > 404.html
          echo "<!doctype html><meta charset='utf-8'><title>VoltAIRepair</title><meta http-equiv='refresh' content='0; url=/VoltAIRepair/admin/index.html'><script>location.replace('/VoltAIRepair/admin/index.html');</script>" > index.html

      - name: Commit and push
        run: |
          git config user.name "voltai-automation"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "auto-cleanup: refreshed essential pages" || echo "No changes"
          git push