name: AI Auto Apply

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  apply:
    if: github.event.comment.body && startsWith(github.event.comment.body, 'ONAY:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract command text
        id: extract
        run: |
          body="${{ github.event.comment.body }}"
          echo "COMMAND=${body#ONAY: }" >> $GITHUB_ENV

      - name: Apply command to panel.json (bash only)
        run: |
          mkdir -p data
          if [ ! -f data/panel.json ]; then echo '{"dailyReport":{"urgent":[]}}' > data/panel.json; fi
          tmp=$(mktemp)
          jq --arg cmd "$COMMAND" '.dailyReport.urgent += [$cmd]' data/panel.json > "$tmp" && mv "$tmp" data/panel.json

      - name: Commit and Push
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add data/panel.json
          git commit -m "Auto apply ONAY update: $COMMAND" || echo "No changes to commit"
          git push