name: AI Auto Apply

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  apply:
    if: github.event.comment.body && startsWith(github.event.comment.body, 'ONAY:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract command text
        id: extract
        run: |
          body="${{ github.event.comment.body }}"
          echo "COMMAND=${body#ONAY: }" >> $GITHUB_ENV

      - name: Apply command to panel.json
        run: |
          mkdir -p data
          if [ ! -f data/panel.json ]; then echo '{"dailyReport":{"urgent":[]}}' > data/panel.json; fi
          node -e "
          const fs=require('fs');
          const d=JSON.parse(fs.readFileSync('data/panel.json'));
          d.dailyReport.urgent.push(process.env.COMMAND);
          fs.writeFileSync('data/panel.json',JSON.stringify(d,null,2));
          "

      - name: Commit and Push
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add data/panel.json
          git commit -m 'Auto apply ONAY update'
          git push