name: Update Panel Data

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'   # 30 dakikada bir otomatik

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare / Merge panel.json
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data

          # panel.json yoksa başlangıç dosyası oluştur
          if [ ! -f data/panel.json ]; then
            cat > data/panel.json <<'JSON'
{
  "totals": { "records": 1284, "new24h": 36, "completionPct": 36 },
  "updatedAt": "1970-01-01T00:00:00Z"
}
JSON
          fi

          NOW=$(date -u +"%Y-%m-%d")

          # Günlük rapor geçici dosyası (istedikçe bu listeyi güncelleriz)
          cat > data/daily-report-tmp.json <<'JSON'
{
  "dailyReport": {
    "date": "__NOW__",
    "newSourcesTop10": [
      "ifixit/iphone-11-charging-guide",
      "apple-discussions/panic-0x8000_002-thread",
      "gsmhosting/iphone-11-tristar-qc",
      "notion/atlas-build-notes-#23",
      "youtube/board-repair-lab-tristar-measure",
      "reddit/ios-panic-log-fixes",
      "medium/dfu-diagnosis-ios17",
      "apple-security/kernel-panic-doc",
      "wikipedia/lightning-pinout",
      "github/boardview-tools"
    ],
    "sponsorsLeads": ["JBC Tools (warm)", "QUCC Battery (cold)", "Kaisi (warm)"],
    "affiliateBlocks": ["AtlasBookNet-Amazon-US", "AtlasBookNet-Aliexpress", "AtlasBookNet-Tooling-Bundle"],
    "urgent": [
      "Fix: Update-Panel workflow cron drift",
      "Add: Panic code map for iOS 18.x",
      "Docs: Measurement photos for iPhone 12 PM VBUS rail"
    ]
  }
}
JSON

          # Tarih yerini doldur
          sed -i "s/__NOW__/${NOW}/" data/daily-report-tmp.json

          # Python ile birleştir
          python3 - <<'PY'
import json
p='data/panel.json'; q='data/daily-report-tmp.json'
a=json.load(open(p)); b=json.load(open(q))
a['dailyReport']=b['dailyReport']
json.dump(a, open(p,'w'), indent=2, ensure_ascii=False)
print("Merged dailyReport into panel.json")
PY

          rm -f data/daily-report-tmp.json

      - name: Commit & Push if changed
        shell: bash
        run: |
          git config user.name  "voltai-operator"
          git config user.email "operator@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "chore(panel): update dailyReport"
            git push
          else
            echo "No changes to commit."
          fi